'''
Problem 2

Each new term in the Fibonacci sequence is 
generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

Find the sum of all the even-valued terms in 
the sequence which do not exceed four million.
'''

value = 0
old, new = 0, 1

while new < 4000000:
    old, new = new, old + new

    if not new % 2:
        value = value + new
    
print value

